Universal Selector + Code refactor
gastonrod/SIA pull request #1
Opened 2018-05-22 02:09 UTC by gastonrod

Mirense el commit wachis

2018-05-23 01:50 UTC, foviedoITBA commented on src/engine/selection/AccumulatedSumSelector.java
> +public abstract class AccumulatedSumSelector {
Esta clase no tiene porqué ser pública. Alcanza y sobra con package-private (sin modificador de acceso).

2018-05-23 01:53 UTC, foviedoITBA commented on src/engine/selection/AccumulatedSumSelector.java
> +    int search(double[] arr, double key) {
Este método no opera sobre nada del selector, así que no tiene porqué ser un método de instancia. De hecho, parece un método auxiliar que no debería ni siquiera estar dentro de esta clase.

2018-05-23 01:56 UTC, gastonrod commented on src/engine/selection/AccumulatedSumSelector.java
> +    int search(double[] arr, double key) {
tru, al princpio lo usaban ambos y quedó

2018-05-23 01:59 UTC, foviedoITBA commented on src/engine/selection/AccumulatedSumSelector.java
> +    Individual pop[];
Estos tres miembros no tienen porqué ser package-private. Si no van a tener getters y/o setters, por lo menos que sean `protected`.

2018-05-23 02:02 UTC, foviedoITBA commented on src/engine/selection/RouletteSelector.java
> +public class RouletteSelector extends AccumulatedSumSelector implements Selector {
Si todos los `AccumulatedSumSelector`s van a ser `Selector`s, entonces que implementen ellos la interfaz con un método abstracto.

2018-05-23 02:05 UTC, foviedoITBA commented on src/engine/selection/RouletteSelector.java
> +            selectedIndividuals.add(pop[super.search(accumulatedSum, Math.random())]);
Me gusta que hayas ido por el camino de la búsqueda binaria, pero lamentablemente no está bien implementada. Mirá cuidadosamente el método que pronto dejará de ser `search`. Si le pasás un número que está por encima del más grande te va a devolver la longitud del arreglo, y esto te va a tirar un `ArrayIndexOutOfBounds`. Pensá bien los casos borde.

2018-05-23 02:06 UTC, foviedoITBA commented on src/engine/selection/UniversalSelector.java
> +public class UniversalSelector extends AccumulatedSumSelector implements Selector {
Nuevamente la idea de que `AccumulatedSumSelector` implemente `Selector` de forma abstracta.

2018-05-23 02:07 UTC, foviedoITBA commented on src/engine/selection/UniversalSelector.java
> +            selectedIndividuals.add(pop[super.search(accumulatedSum, rand)]);
Tenés el mismo problema del método `search`.

2018-05-23 02:11 UTC, foviedoITBA commented on src/engine/selection/UniversalSelector.java
> +            double rand = (r + (double) i - 1.0) / (double) k;
Con que o numerador o denominador sean `double` alcanza, no hay que castear los dos. De hecho, con restar 1.0 ya estás casteando implícitamente el numerador, por lo que los dos casteos explícitos son innecesarios.

2018-05-23 02:22 UTC, foviedoITBA commented on src/engine/selection/AccumulatedSumSelector.java
> +    int search(double[] arr, double key) {
Es un método que lo usan todos los selectores, pero no tiene nada que ver con un selector. Hace búsqueda binaria sobre un arreglo de números y te devuelve algo así como la posición de la cota inferior. Que lo usen todos los selectores no es excusa para meterlo adentro de la clase.

2018-05-23 02:46 UTC, foviedoITBA requested changes
Lo más importante es el uso de la búsqueda binaria que no está bien implementada/utilizada.

2018-05-23 17:53 UTC, gastonrod commented on src/engine/selection/RouletteSelector.java
> +            selectedIndividuals.add(pop[super.search(accumulatedSum, Math.random())]);
No está mal implementada, Math.random() devuelve numeros entre [0,1), y accumulatedSum termina con el último número teniendo el valor de 1 (porque es la suma de todas las fitnessess (o w/e) relativas), por lo que nunca al método nunca le va a llegar una key mayor al máximo del array.

2018-05-24 16:47 UTC, foviedoITBA commented on src/engine/selection/AccumulatedSumSelector.java
> +            accumulatedSum[i] = fitness;
No estás acumulando nada. Imagino que debería ser `accumulatedSum[i] = totalFirness;`.

2018-05-24 16:51 UTC, foviedoITBA commented on src/engine/selection/AccumulatedSumSelector.java
> +    int lowerBoundSearch(double[] arr, double key) {
Creo que sería mejor que se llame `upperBoundSearch`, ya que te devuelve el índice del primero que no es más chico. Por otro lado, te reitero que esto no va en esta clase porque no tiene nada que ver con un `AcumulatedSumSelector`, más allá de que todas sus subclases lo usen.

2018-05-24 16:52 UTC, foviedoITBA commented on src/engine/selection/RouletteSelector.java
> +            selectedIndividuals.add(pop[super.search(accumulatedSum, Math.random())]);
Está mal porque `accumulatedSum` no está necesariamente ordenado ni tiene 1 en su última posición. Fijate cómo lo estás inicializando.

2018-05-24 16:54 UTC, foviedoITBA requested changes
Mirá los comentarios nuevos y mis respuestas a comentarios tuyos que quedaron "outdated".

2018-05-24 18:12 UTC, gastonrod commented on src/engine/selection/AccumulatedSumSelector.java
> +    int lowerBoundSearch(double[] arr, double key) {
Jajaja la concha de tu madre

2018-05-24 18:14 UTC, gastonrod commented on src/engine/selection/AccumulatedSumSelector.java
> +            accumulatedSum[i] = fitness;
Manquie duro

2018-05-24 18:16 UTC, gastonrod commented on src/engine/selection/RouletteSelector.java
> +            selectedIndividuals.add(pop[super.search(accumulatedSum, Math.random())]);
Estaba mal hecho el accumulated sum, pero este uso está bien.

2018-05-25 18:53 UTC, foviedoITBA requested changes
Te copio acá el comentario respecto al método de búsqueda binaria porque evidentemente no lo ves: "Es un método que lo usan todos los selectores, pero no tiene nada que ver con un selector. Hace búsqueda binaria sobre un arreglo de números y te devuelve algo así como la posición de la cota inferior. Que lo usen todos los selectores no es excusa para meterlo adentro de la clase."

2018-05-25 19:24 UTC, foviedoITBA approved these changes
Listo,

2018-05-25 19:24 UTC, merged