Added the tourney selectors
gastonrod/SIA pull request #2
Opened 2018-05-22 12:17 UTC by gastonrod

Por ahi es medio ineficiente, lo hice pensando mas en que quede lindo.
Si no va lo mejoramos.

2018-05-22 23:34 UTC, axelfratoni approved these changes
Cambiaría los nombres de un par de variables y documentaría pero tiene pinta de andar piola.

2018-05-22 23:34 UTC, axelfratoni commented on src/engine/selection/TourneySelector.java
> +    Individual getWinner(int[] winners, FitnessFunction fitnessFunction){
Lo que llamas winners en `int[] winners` no serian los participantes? De ahi sale un solo winner.

2018-05-22 23:34 UTC, axelfratoni commented on src/engine/selection/TourneySelector.java
> +    int m;
Un poco mas descriptivo el nombre estaria mejor.

2018-05-23 02:25 UTC, foviedoITBA commented on src/engine/selection/TourneySelector.java
> +    protected int m;
¿Qué es `m`? La misma pregunta para todos los lugares en los que aparece.

2018-05-23 02:28 UTC, foviedoITBA commented on src/engine/selection/TourneySelector.java
> +    TourneySelector(int m){
`protected`

2018-05-23 02:31 UTC, foviedoITBA commented on src/engine/selection/TourneySelector.java
> +    int[] getParticipantsIndexes(){
`protected`

2018-05-23 02:32 UTC, foviedoITBA commented on src/engine/selection/TourneySelector.java
> +    Individual getWinner(int[] participants, FitnessFunction fitnessFunction){
`protected`

2018-05-23 02:39 UTC, foviedoITBA commented on src/engine/selection/ProbabilisticTourneySelector.java
> +        super(2);
Este número mágico podría ser una constante con un número más descriptivo.

2018-05-23 02:41 UTC, foviedoITBA commented on src/engine/selection/ProbabilisticTourneySelector.java
> +    private int p;
Según las filminas, este valor es siempre 0.75. ¿Para qué lo parametrizamos?

2018-05-23 02:42 UTC, foviedoITBA commented on src/engine/selection/ProbabilisticTourneySelector.java
> +        this.p = (int) (p * 100);
¿Para qué lo transformás en un entero? Podés dejarlo como `double` y usar `Math.random()` para sacar un número entre 0 y 1.

2018-05-23 02:44 UTC, foviedoITBA requested changes
A simple vista parece estar bien la funcionalidad, pero hay algunas cuestiones para revisar.

2018-05-24 16:56 UTC, foviedoITBA commented on src/engine/selection/TourneySelector.java
> +    TourneySelector(int participantsPerDuel){
Dije `protected`.

2018-05-24 16:56 UTC, foviedoITBA commented on src/engine/selection/TourneySelector.java
> +    int[] getParticipantsIndexes(){
Dije `protected`.

2018-05-24 16:57 UTC, foviedoITBA commented on src/engine/selection/TourneySelector.java
> +    Individual getWinner(int[] participants, FitnessFunction fitnessFunction){
Dije `protected`.

2018-05-24 16:58 UTC, foviedoITBA commented on src/engine/selection/ProbabilisticTourneySelector.java
> +    private int participants = 2;
Si no va a cambiar debería ser `final`. Y si es la misma para todas las instancias de esta clase debería ser `static`.

2018-05-24 16:59 UTC, foviedoITBA commented on src/engine/selection/ProbabilisticTourneySelector.java
> +    private double p = 0.75;
Si no va a cambiar debería ser `final`. Y si es la misma para todas las instancias de esta clase debería ser `static`.

2018-05-24 17:01 UTC, foviedoITBA requested changes
Mirá bien los comentarios porque creo que te comiste un par.

2018-05-25 19:00 UTC, foviedoITBA approved these changes
Listo.

2018-05-25 19:13 UTC, merged