Non-uniform mutator done.
gastonrod/SIA pull request #4
Opened 2018-05-24 16:11 UTC by axelfratoni

Extracted the uniform mutator's behaviour to an abstract class.
Individual's interface now requires knowleadge of its current generation.

2018-05-24 18:46 UTC, foviedoITBA commented on src/engine/mutation/NonUniformSinglePointMutator.java
> +public class NonUniformSinglePointMutator extends AbstractSinglePointMutator implements Mutator{
`AbstractSinglePointMutator` ya implementa `Mutator`, no hace ponerlo acá también.

2018-05-24 18:46 UTC, foviedoITBA commented on src/engine/mutation/AbstractSinglePointMutator.java
> +    AbstractSinglePointMutator(double probability) {
`protected`

2018-05-24 18:46 UTC, foviedoITBA commented on src/engine/mutation/AbstractSinglePointMutator.java
> +    void mutateSinglePoint(Individual individual) {
`protected`

2018-05-24 18:54 UTC, foviedoITBA commented on src/engine/VariationFunction.java
> +public interface VariationFunction {
Si esta interfaz va a estar dirada acá, dudo que haga falta que sea `public`. De todas formas, me parece mejor tener un paquete con esta interfaz y todas las clases que la implementen.

2018-05-24 18:59 UTC, foviedoITBA commented on src/engine/mutation/NonUniformSinglePointMutator.java
> +        super(0);
Magic number?

2018-05-24 19:00 UTC, foviedoITBA commented on src/engine/mutation/NonUniformSinglePointMutator.java
> +    public void mutate(Individual individual) {
Me parece que podríamos agregarle la generación como parámetro del método `mutate` en la interfaz `Mutator`. Podemos discutirlo.

2018-05-24 19:03 UTC, foviedoITBA commented on src/engine/mutation/AbstractSinglePointMutator.java
> +    double probability;
Sería mejor que este campo no exista, que el constructor de `UniformSelector` reciba la probabilidad en el constructor y que el método `mutateSinglePoint` la reciba como parámetro.

2018-05-24 19:04 UTC, foviedoITBA requested changes
Hay que hacer un pequeño refactor. Podemos hacerlo juntos mañana.

2018-05-24 19:13 UTC, gastonrod commented on src/engine/VariationFunction.java
> +public interface VariationFunction {
Lo mismo se podría decir de la FitnessFunction, no? O esa hay una sola?

2018-05-24 19:18 UTC, gastonrod requested changes

2018-05-24 19:18 UTC, gastonrod commented on src/engine/mutation/AbstractSinglePointMutator.java
> +    AbstractSinglePointMutator(double probability) {
Agregaría un constructor vacío o algo así para que el non-uniform no tenga que hacer ninguna sideada, si siempre que le llaman al mutate setea la probabilidad a la que corresponda. No hace falta inicializarla.

2018-05-25 16:36 UTC, axelfratoni commented on src/engine/mutation/AbstractSinglePointMutator.java
> +    double probability;
`nonUniformMutator` también necesita saber la probabilidad para no tener que evaluarla por cada individuo dentro de una generación.

2018-05-25 19:06 UTC, foviedoITBA commented on src/engine/mutation/AbstractSinglePointMutator.java
> +    double probability;
La puede saber sin necesidad de que esté acá. En el `UniformMutator` la probabilidad es siempre la misma. En el `NonUniformMutator` cambia de generación en generación. Me parece una diferencia suficientemente grande como para que no esté como una variable en `AbstractSinglePointMutator`. Así como está, nada le impide al `UniformMutator` cambiar la probabilidad de mutación.

2018-05-25 19:10 UTC, foviedoITBA commented on src/engine/mutation/NonUniformSinglePointMutator.java
> +    public NonUniformSinglePointMutator(VariationFunction variationFunction, int firstGeneration) {
¿Para qué recibe `firstGeneration`como parámetro si lo va a recibir la primera vez que se llame a `mutate`?

2018-05-25 19:12 UTC, foviedoITBA commented on src/engine/variation/VariationFunction.java
> +    double eval(int initialValue);
¿Por qué el parámetro se llama `initialValue`? ¿No es el número de generación?

2018-05-25 19:49 UTC, foviedoITBA approved these changes
Listo.

2018-05-25 19:50 UTC, merged